PM-VLN url update

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -61,8 +61,8 @@ if ! git diff-index --quiet HEAD --; then
     echo "Changes to the following files are uncommitted:"
     git diff-index --name-only HEAD --
     echo "Please commit the changes before proceeding."
-    echo "Aborting."
-    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+    #echo "Aborting."
+    #[[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
 # Check if there are any untracked files
@@ -70,8 +70,8 @@ if ! test -z "$(git ls-files --exclude-standard --others)"; then
     echo "There are untracked files:"
     git ls-files --exclude-standard --others
     echo "Please commit those files or stash them before proceeding."
-    echo "Aborting."
-    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+    #echo "Aborting."
+    #[[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
 # Switch to source branch (creates it if necessary from the current branch)
